In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv(r'C:\Users\alexb\PycharmProjects\DataScience-SQL-Tableau\data\Absenteeism_Preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0     False     False     False      True      7                1   
1     False     False     False     False      7                1   
2     False     False     False      True      7                2   
3      True     False     False     False      7                3   
4     False     False     False      True      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

np.float64(3.0)

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0     False     False     False      True      7                1   
1     False     False     False     False      7                1   
2     False     False     False      True      7                2   
3      True     False     False     False      7                3   
4     False     False     False      True      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
##Comment about targets

In [10]:
targets.sum() / targets.shape[0]

np.float64(0.45571428571428574)

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week','Daily Work Load Average','Distance to Work'], axis=1)

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  Age  \
0     False     False     False      True      7                     289   33   
1     False     False     False     False      7                     118   50   
2     False     False     False      True      7                     179   38   
3      True     False     False     False      7                     279   39   
4     False     False     False      True      7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [13]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [14]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
# columns_to_scale = ['Month', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index',
#        'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [20]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\alexb\PycharmProjects\DataScience-SQL-Tableau\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:4316: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [22]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0       False     False     False      True  0.182726                1.005844   
1       False     False     False     False  0.182726               -1.574681   
2       False     False     False      True  0.182726               -0.654143   
3        True     False     False     False  0.182726                0.854936   
4       False     False     False      True  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695      True     False     False     False -0.388293               -0.654143   
696      True     False     False     False -0.388293                0.040034   
697      True     False     False     False -0.388293                1.624567   
698     False     False     False      True -0.388293                0.190942   
699     False     False     False      True -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431  -0.447980  0.880469  0.268487  
1    2.130803         1.002633  -0.447980 -0.019280 -0.589690  
2    0.248310         1.002633  -0.447980 -0.919030 -0.589690  
3    0.405184        -0.643782  -0.447980  0.880469 -0.589690  
4   -0.536062         0.767431  -0.447980  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186   2.232242  0.880469 -0.589690  
696 -1.320435        -0.643782  -0.447980 -0.019280  1.126663  
697 -1.320435        -0.408580   2.232242 -0.919030 -0.589690  
698 -0.692937        -0.408580   2.232242 -0.919030 -0.589690  
699  0.562059        -0.408580  -0.447980 -0.019280  0.268487  

[700 rows x 11 columns]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
 134     False     False     False      True -1.530333               -1.574681   
 65      False     False     False      True  1.039256               -0.654143   
 645     False     False     False      True -0.959313               -0.654143   
 44      False     False     False      True  0.753746               -1.016322   
 503     False     False     False      True  0.753746                0.040034   
 ..        ...       ...       ...       ...       ...                     ...   
 118     False     False     False      True -1.530333               -0.578689   
 512     False     False     False      True  1.039256               -1.574681   
 55      False     False     False     False  0.753746               -1.574681   
 501     False     False     False      True  0.753746                0.387122   
 445     False     False     False      True -0.102784                0.568211   
 
           Age

In [25]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [26]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [28]:
reg = LogisticRegression()

In [29]:
reg.fit(x_train, y_train)

LogisticRegression()

In [30]:
reg.score(x_train, y_train)

0.7732142857142857

In [31]:
model_outputs = reg.predict(x_train)

In [32]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [34]:
np.sum(model_outputs == y_train)

np.int64(433)

In [35]:
model_outputs.shape[0]

560

In [36]:
reg.intercept_

array([-1.67498624])

In [37]:
reg.coef_

array([[ 2.79375844,  0.95359362,  3.10546299,  0.83085358,  0.15852833,
         0.60468158, -0.17056711,  0.27780477, -0.08424352,  0.34734043,
        -0.27736499]])

In [38]:
feature_name = unscaled_inputs.columns.values

In [39]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0                 Reason_1     2.793758
1                 Reason_2     0.953594
2                 Reason_3     3.105463
3                 Reason_4     0.830854
4                    Month     0.158528
5   Transportation Expense     0.604682
6                      Age    -0.170567
7          Body Mass Index     0.277805
8                Education    -0.084244
9                 Children     0.347340
10                    Pets    -0.277365

In [40]:
summary_table.index = summary_table.index + 1

In [41]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [42]:
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -1.674986
1                 Reason_1     2.793758
2                 Reason_2     0.953594
3                 Reason_3     3.105463
4                 Reason_4     0.830854
5                    Month     0.158528
6   Transportation Expense     0.604682
7                      Age    -0.170567
8          Body Mass Index     0.277805
9                Education    -0.084244
10                Children     0.347340
11                    Pets    -0.277365

In [43]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [44]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature Name  Coefficient  Odds_ratio
3                 Reason_3     3.105463   22.319550
1                 Reason_1     2.793758   16.342326
2                 Reason_2     0.953594    2.595018
4                 Reason_4     0.830854    2.295277
6   Transportation Expense     0.604682    1.830669
10                Children     0.347340    1.415298
8          Body Mass Index     0.277805    1.320228
5                    Month     0.158528    1.171785
9                Education    -0.084244    0.919207
7                      Age    -0.170567    0.843186
11                    Pets    -0.277365    0.757778
0                Intercept    -1.674986    0.187311

In [45]:
reg.score(x_test, y_test)

0.75

In [47]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71328706, 0.28671294],
       [0.5868545 , 0.4131455 ],
       [0.44134189, 0.55865811],
       [0.78134024, 0.21865976],
       [0.08390289, 0.91609711],
       [0.33416409, 0.66583591],
       [0.29892189, 0.70107811],
       [0.13152486, 0.86847514],
       [0.78543137, 0.21456863],
       [0.74884244, 0.25115756],
       [0.493633  , 0.506367  ],
       [0.22472141, 0.77527859],
       [0.07133356, 0.92866644],
       [0.73452626, 0.26547374],
       [0.30947706, 0.69052294],
       [0.54998141, 0.45001859],
       [0.55004133, 0.44995867],
       [0.53881581, 0.46118419],
       [0.40123117, 0.59876883],
       [0.05377404, 0.94622596],
       [0.69951499, 0.30048501],
       [0.78134024, 0.21865976],
       [0.41930999, 0.58069001],
       [0.41930999, 0.58069001],
       [0.24735108, 0.75264892],
       [0.74484338, 0.25515662],
       [0.5097579 , 0.4902421 ],
       [0.85787351, 0.14212649],
       [0.20371958, 0.79628042],
       [0.78134024, 0.21865976],
       [0.

In [48]:
predicted_proba.shape

(140, 2)

In [49]:
predicted_proba[:,1]

array([0.28671294, 0.4131455 , 0.55865811, 0.21865976, 0.91609711,
       0.66583591, 0.70107811, 0.86847514, 0.21456863, 0.25115756,
       0.506367  , 0.77527859, 0.92866644, 0.26547374, 0.69052294,
       0.45001859, 0.44995867, 0.46118419, 0.59876883, 0.94622596,
       0.30048501, 0.21865976, 0.58069001, 0.58069001, 0.75264892,
       0.25515662, 0.4902421 , 0.14212649, 0.79628042, 0.21865976,
       0.37004524, 0.68044644, 0.68566587, 0.52896558, 0.21865976,
       0.53505912, 0.22229498, 0.73722935, 0.40442372, 0.60529027,
       0.21102548, 0.45092708, 0.23833688, 0.40052068, 0.8272578 ,
       0.56837392, 0.69220234, 0.28671294, 0.22009623, 0.20358828,
       0.57467471, 0.32857895, 0.66583591, 0.27021398, 0.83367886,
       0.43525204, 0.88375813, 0.23187918, 0.33499954, 0.34515676,
       0.69712688, 0.6556909 , 0.29299117, 0.79234144, 0.20804092,
       0.26856306, 0.08822409, 0.22229498, 0.73292302, 0.30223781,
       0.22229498, 0.2921123 , 0.90412168, 0.45989651, 0.60157

In [51]:
import pickle

In [52]:
with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [53]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler,file)